config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :answers
  resources :questions
  devise_for :users
  resources :answers, :except => [:index, :show]
  root 'home#index'
  resources :users
  get 'users/new'
#  get '*path' => redirect('/')

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	  def index
	  	if current_user
	    	@questions = current_user.questions.search(params[:search]).latest.paginate(page: params[:page], per_page: 5)
	    else
		    @questions = Question.search(params[:search]).latest.paginate(page: params[:page], per_page: 5)
			respond_to do |format|
		      format.html
		      format.json { render json: @questions }
		    end
    	end
	   end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h3><b>All Questions</b></h3>



<% if @questions.count > 0 %>
<ul class="list-group">
    <% @questions.order('created_at DESC').each do |question| %>
      <div class="panel panel-primary">
        <div class="panel-heading">
       <% if current_user %>
          <a href="<%=question_path(question) %>">
            <h4 class="panel-title"><%=  question.description %></h4>
            
            <!-- <button type="button" class="btn btn-info" style="margin: -60px 0px 0px 1000px">Views: <%= question.impressions.count %>  </button>  -->
          </a>
          <% else %>
          <a href="">
            <button type="button" class="btn btn-primary" style="float: right;">
                     <span class="badge badge-light"><%= question.tags %></span>
                </button>
              <h4 class="panel-title"><%=  question.description %></h4><!-- <button type="button" class="btn btn-info" style="margin: -60px 0px 0px 577px">Viewed by <%= question.impressions.count %>  </button>  --></a>
          <% end %>
        </div>
        <% if question.answers.size > 0 %>
          <div class="alert alert-success" role="alert"><%= question.answers.size %> best solutions for this question.</div>
        <% else %>
          <div class="alert alert-danger" role="alert">There is no answers for this question, please add your answer to help the questioner.</div>
        <% end %>
          <% if current_user %>
          <% else %>
          <b style="font-style: italic;color: darkred">Ask a question or Share your answers by</b>
          <a href="/users/sign_up" class="badge badge-primary">Register</a> or 
          <a href="/users/sign_in" class="badge badge-success">Login</a>
          <% end %>
          <% question.answers.order('created_at DESC').each do |answer| %>
          <div class="panel panel-default">
            <div class="card">
              <p class="card-header"><b><%= answer.user.email %> </b> answered <%= time_ago_in_words(answer.created_at) %> ago. </p>

              <div class="card-body">
                <p class="card-text"><%= answer.content %></p>
                 <b style="float: left;"> - <%= answer.user.email %></b>

                <button type="button" class="btn btn-primary" style="float: right;">
                     <span class="badge badge-light"><%= question.tags %></span>
                </button>
                <br>
                <% if answer.user == current_user %>
                    <%= link_to 'Edit', edit_answer_path(answer), :class=>"btn btn-info"%>
                <% end %>
              </div>
            </div>
          </div>
          <% end %>
          <hr>
        </div>
      <% end %>
      </ul>
<% else %>
            <div class="panel panel-default">
                <div class="card">
                  <p class="card-header">No data found </p>
                </div>
              </div>

<% end %>

<%= will_paginate @questions%>

<style type="text/css">
  .pull-right{
    float: right;
  }

  .pagination .current {
  display: inline-block;
    padding: 8px 16px;
    text-decoration: none;
    display: inline-block;
    color: black;
    float: left;
    transition: background-color .3s;
    border: 1px solid #ddd;
}

.pagination a:hover:not(.active) {background-color: #ddd;}

.pagination a {
  color: black;
  float: left;
  padding: 8px 16px;
  text-decoration: none;
  transition: background-color .3s;
  border: 1px solid #ddd;
}
</style>