config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :answers
  resources :questions
  devise_for :users
  resources :answers, :except => [:index, :show]
  root 'home#index'
  resources :users
  get 'users/new'
#  get '*path' => redirect('/')

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </head>
  <body>
  <nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="/">Q/A Platform</a>
  <form class="form-inline">
    <%= form_tag questions_path, :method => 'get', :class => "navbar-form navbar-left" do %>
              <div class="form-group">
                <%= text_field_tag :search, params[:search], :class => "form-control"%>
              </div>
              <button type="submit" class="btn btn-default">Search</button>
            <% end %>
          <% if user_signed_in? %>
            <ul class="navbar-form navbar-right">
              <%= link_to (button_tag "All Question", type: 'button', :class => 'btn btn-info'), questions_path %>
              <%= link_to (button_tag "Ask Question", type: 'button', :class => 'btn btn-danger'), new_question_path %>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"><%= current_user.email %><span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Settings", edit_user_registration_path %></li>
                  <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
                </ul>
              </li>
            </ul>
            <% else %>
            <ul class="navbar-form navbar-right">
              <%= link_to (button_tag "Register", type: 'button', :class => 'btn btn-primary'), new_user_registration_path %>
              <%= link_to (button_tag "Login", type: 'button', :class => 'btn btn-success'), new_user_session_path %>
            </ul>
          <% end %>
    </div>
  </form>
</nav>
    <div class="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>